version: "3.6"
services:
  gregsithole-react-portfolio:
    build:
      context: ./gregsithole-react-portfolio-master
      dockerfile: devops/dev-gregsithole-react-portfolio/gregsithole-react-portfolio/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - gregsithole-react-portfolio
    links:
      - gregsithole-react-portfolio
networks:
  default:
    driver: bridge
